# Raw Data Exploration

Goal: understand the bank export format before writing any production code.

Questions to answer:
- What columns exist and what do they mean?
- What is the date format?
- How are amounts represented? (signed single column, or separate debit/credit?)
- Are there any encoding issues?
- Are there metadata rows above the header?
- What needs cleaning before this data is usable?

In [1]:
from pathlib import Path
import polars as pl

## 1. Locate raw files

In [2]:
raw_dir = Path("../data/raw")
files = list(raw_dir.iterdir())
files

[PosixPath('../data/raw/RELEVE_COMPTE_CHEQUES_1_2026_03_26_16_41_51.csv'),
 PosixPath('../data/raw/RELEVE_LIVRET_A_2026_03_26_16_42_10.csv'),
 PosixPath('../data/raw/RELEVE_LIVRET_DEV._DURABLE_ET_SOLIDAIRE_2026_03_26_16_42_07.csv'),
 PosixPath('../data/raw/.gitkeep')]

## 2. Inspect the raw file

In [3]:
# Set the file to explore
raw_file = files[0]

# Read first few lines as plain text to check encoding and structure
with open(raw_file, encoding="utf-8") as f:
    for i, line in enumerate(f):
        print(repr(line))
        if i >= 9:
            break

'"Date operation";"Date valeur";"Libelle";"Debit";"Credit"\n'
'"25/03/2026";"25/03/2026";"CARTE 23/03 GRAND FRAIS 59VILLENEUVE";"23,95";""\n'
'"25/03/2026";"25/03/2026";"CARTE 23/03 ERIC KAYSER 59340489 CB S";"3,50";""\n'
'"25/03/2026";"25/03/2026";"CARTE 23/03 NYX*DECATHLONSEI VilleneuvedAs";"0,30";""\n'
'"25/03/2026";"25/03/2026";"CARTE 23/03 NYX*DECATHLONSEI VilleneuvedAs";"0,30";""\n'
'"23/03/2026";"23/03/2026";"CARTE 23/03 NETFLIX.COM 18665797172";"7,99";""\n'
'"23/03/2026";"23/03/2026";"CARTE 22/03 CARREFOUR CT LILLE";"67,44";""\n'
'"23/03/2026";"23/03/2026";"CARTE 22/03 LA BULLE CAFE LILLE";"3,20";""\n'
'"23/03/2026";"23/03/2026";"CARTE 21/03 GIFI LILLE 01866 /";"26,98";""\n'
'"23/03/2026";"23/03/2026";"CARTE 21/03 ILEVIA BR METRO MARCQ EN BARO";"2,40";""\n'

## 3. Load with Polars

In [8]:
# Adjust separator, skip_rows, encoding as needed after inspecting above
df = pl.read_csv(raw_file, separator=";")
df.head(10)

shape: (10, 5)
┌────────────────┬─────────────┬─────────────────────────────────┬───────┬────────┐
│ Date operation ┆ Date valeur ┆ Libelle                         ┆ Debit ┆ Credit │
│ ---            ┆ ---         ┆ ---                             ┆ ---   ┆ ---    │
│ str            ┆ str         ┆ str                             ┆ str   ┆ str    │
╞════════════════╪═════════════╪═════════════════════════════════╪═══════╪════════╡
│ 25/03/2026     ┆ 25/03/2026  ┆ CARTE 23/03 GRAND FRAIS 59VILL… ┆ 23,95 ┆        │
│ 25/03/2026     ┆ 25/03/2026  ┆ CARTE 23/03 ERIC KAYSER 593404… ┆ 3,50  ┆        │
│ 25/03/2026     ┆ 25/03/2026  ┆ CARTE 23/03 NYX*DECATHLONSEI V… ┆ 0,30  ┆        │
│ 25/03/2026     ┆ 25/03/2026  ┆ CARTE 23/03 NYX*DECATHLONSEI V… ┆ 0,30  ┆        │
│ 23/03/2026     ┆ 23/03/2026  ┆ CARTE 23/03 NETFLIX.COM 186657… ┆ 7,99  ┆        │
│ 23/03/2026     ┆ 23/03/2026  ┆ CARTE 22/03 CARREFOUR CT LILLE  ┆ 67,44 ┆        │
│ 23/03/2026     ┆ 23/03/2026  ┆ CARTE 22/03 LA BULLE CAFE LILL… ┆ 3,20  ┆        │
│ 23/03/2026     ┆ 23/03/2026  ┆ CARTE 21/03 GIFI LILLE 01866 /  ┆ 26,98 ┆        │
│ 23/03/2026     ┆ 23/03/2026  ┆ CARTE 21/03 ILEVIA BR METRO MA… ┆ 2,40  ┆        │
│ 23/03/2026     ┆ 23/03/2026  ┆ CARTE 21/03 GDE PHIE DE PARI L… ┆ 1,90  ┆        │
└────────────────┴─────────────┴─────────────────────────────────┴───────┴────────┘

In [9]:
# Schema — column names and inferred types
print(df.schema)

Schema({'Date operation': String, 'Date valeur': String, 'Libelle': String, 'Debit': String, 'Credit': String})

In [10]:
# Shape and basic stats
print(f"Rows: {df.height}, Columns: {df.width}")
df.describe()

Rows: 4925, Columns: 5

shape: (9, 6)
┌────────────┬────────────────┬─────────────┬───────────────────────────────┬─────────┬────────┐
│ statistic  ┆ Date operation ┆ Date valeur ┆ Libelle                       ┆ Debit   ┆ Credit │
│ ---        ┆ ---            ┆ ---         ┆ ---                           ┆ ---     ┆ ---    │
│ str        ┆ str            ┆ str         ┆ str                           ┆ str     ┆ str    │
╞════════════╪════════════════╪═════════════╪═══════════════════════════════╪═════════╪════════╡
│ count      ┆ 4925           ┆ 4925        ┆ 4925                          ┆ 4925    ┆ 4925   │
│ null_count ┆ 0              ┆ 0           ┆ 0                             ┆ 0       ┆ 0      │
│ mean       ┆ null           ┆ null        ┆ null                          ┆ null    ┆ null   │
│ std        ┆ null           ┆ null        ┆ null                          ┆ null    ┆ null   │
│ min        ┆ 01/01/2026     ┆ 01/01/2025  ┆ ANN CARTE CARREFOUR SCT LILLE ┆         ┆        │
│ 25%        ┆ null           ┆ null        ┆ null                          ┆ null    ┆ null   │
│ 50%        ┆ null           ┆ null        ┆ null                          ┆ null    ┆ null   │
│ 75%        ┆ null           ┆ null        ┆ null                          ┆ null    ┆ null   │
│ max        ┆ 31/12/2025     ┆ 31/12/2025  ┆ vers NOYELLE FONTAINE         ┆ 9990,00 ┆ 95,98  │
└────────────┴────────────────┴─────────────┴───────────────────────────────┴─────────┴────────┘

## 4. Findings

Fill this in as you explore:

- **Columns:**
- **Date format:**
- **Amount representation:**
- **Encoding:**
- **Issues found:**
- **Transformations needed:**